language: ruby
rvm:
  - 2.6.6
before_install: gem install bundler -v 2.2.5
before_script:
  - cp config/config.travis.yml config/config.yml
script:
  - bundle exec rspec
services:
  - rabbitmq
  - redis

addons:
  apt:
    packages:
      - rabbitmq-server
  code_climate:
      repo_token: 64e1043b9bd0f931bbe0a333411d1aeb92f91748e3a21397a0d169f13ae0c970
