default: &default
  application_name: GorgLdapDaemon
  application_id: ldapd-t


  rabbitmq_host: localhost
  rabbitmq_port: 5672
  rabbitmq_vhost: "/"
  rabbitmq_queue_name: ldapd
  rabbitmq_event_exchange_name: agoram_event_exchange
  rabbitmq_deferred_time: 1000
  rabbitmq_max_attempts: 5
  rabbitmq_user: guest
  rabbitmq_password: guest

  logger_level: debug

  log_routing_key: "log"

  admin_user_id: alexandre.narbonne@poubs.org


development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
